# Generated by Django 3.2 on 2021-06-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(serialize=False, verbose_name='created_at')),
                ('creator', models.CharField(max_length=120, serialize=False, verbose_name='creator')),
                ('updated_at', models.DateTimeField(serialize=False, verbose_name='updated_at')),
                ('updater', models.CharField(max_length=120, serialize=False, verbose_name='updater')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('salary_table', models.IntegerField(choices=[(1010, '行（一）'), (1020, '行（二）'), (1110, '専門行政'), (1210, '税務'), (1310, '公安（一）'), (1320, '公安（二）'), (1410, '海（一）'), (1420, '海（二）'), (1510, '教（一）'), (1520, '教（二）'), (1610, '研究'), (1710, '医（一）'), (1720, '医（二）'), (1730, '医（三）'), (1810, '福祉'), (1910, '任研（一）'), (1920, '任研（二）'), (1930, '特任研'), (2010, '専門スタッフ'), (2110, '指定職')], default=1010, verbose_name='salary table')),
                ('salary_level', models.IntegerField(verbose_name='salary level')),
                ('salary_no', models.IntegerField(verbose_name='salary no')),
                ('salary_monthly', models.IntegerField(verbose_name='salary monthly')),
                ('salary_adjustment', models.IntegerField(verbose_name='salary adjustment')),
            ],
            options={
                'verbose_name': 'salary table',
                'verbose_name_plural': 'salary table',
                'ordering': ['-start_date', 'salary_table', 'salary_level', 'salary_no'],
                'permissions': [('import_salary_table', 'Can import salary_table'), ('export_salary_table', 'Can export salary_table')],
            },
        ),
        migrations.CreateModel(
            name='SalaryTableExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(serialize=False, verbose_name='created_at')),
                ('creator', models.CharField(max_length=120, serialize=False, verbose_name='creator')),
                ('updated_at', models.DateTimeField(serialize=False, verbose_name='updated_at')),
                ('updater', models.CharField(max_length=120, serialize=False, verbose_name='updater')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('salary_table', models.IntegerField(choices=[(1010, '行（一）'), (1020, '行（二）'), (1110, '専門行政'), (1210, '税務'), (1310, '公安（一）'), (1320, '公安（二）'), (1410, '海（一）'), (1420, '海（二）'), (1510, '教（一）'), (1520, '教（二）'), (1610, '研究'), (1710, '医（一）'), (1720, '医（二）'), (1730, '医（三）'), (1810, '福祉'), (1910, '任研（一）'), (1920, '任研（二）'), (1930, '特任研'), (2010, '専門スタッフ'), (2110, '指定職')], default=1010, verbose_name='salary table')),
                ('sheet_name', models.CharField(max_length=10, verbose_name='シート名')),
                ('rows', models.IntegerField(default=1, verbose_name='級')),
                ('cols', models.IntegerField(default=1, verbose_name='号俸')),
                ('sny_flg', models.BooleanField(default=True, verbose_name='再任用有無')),
                ('start_cell', models.CharField(max_length=10, verbose_name='データ開始セル')),
            ],
            options={
                'verbose_name': '俸給表取込エクセル設定',
                'verbose_name_plural': '俸給表取込エクセル設定',
                'db_table': 'salary_table_excel',
                'ordering': ['-start_date', 'salary_table'],
            },
        ),
        migrations.AddConstraint(
            model_name='salarytableexcel',
            constraint=models.UniqueConstraint(fields=('start_date', 'salary_table'), name='salary_table_excel_unique'),
        ),
        migrations.AddConstraint(
            model_name='salarytable',
            constraint=models.UniqueConstraint(fields=('start_date', 'salary_table', 'salary_level', 'salary_adjustment'), name='salary_table_unique'),
        ),
    ]
