# Generated by Django 3.2 on 2021-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(serialize=False, verbose_name='created_at')),
                ('creator', models.CharField(max_length=120, serialize=False, verbose_name='creator')),
                ('updated_at', models.DateTimeField(serialize=False, verbose_name='updated_at')),
                ('updater', models.CharField(max_length=120, serialize=False, verbose_name='updater')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('salary_table', models.CharField(choices=[('GS1', '行（一）'), ('GS2', '行（二）'), ('SGS', '専門行政'), ('ZM', '税務'), ('KA1', '公安（一）'), ('KA2', '公安（二）'), ('KJ1', '海（一）'), ('KJ2', '海（二）'), ('KI1', '教（一）'), ('KI2', '教（二）'), ('KK', '研究'), ('IR1', '医（一）'), ('IR2', '医（二）'), ('IR3', '医（三）'), ('FS', '福祉'), ('NK1', '任研（一）'), ('NK2', '任研（二）'), ('TNK', '特任研'), ('SS', '専門スタッフ'), ('ST', '指定')], max_length=10, verbose_name='salary table')),
                ('salary_level', models.IntegerField(verbose_name='salary level')),
                ('salary_no', models.IntegerField(verbose_name='salary no')),
                ('salary_monthly', models.IntegerField(verbose_name='salary monthly')),
                ('salary_adjustment', models.IntegerField(verbose_name='salary adjustment')),
            ],
            options={
                'verbose_name': 'salary table',
                'verbose_name_plural': 'salary table',
                'ordering': ['-start_date', 'salary_table', 'salary_level', 'salary_no'],
                'permissions': [('import_salary_table', 'Can import salary_table'), ('export_salary_table', 'Can export salary_table')],
            },
        ),
        migrations.AddConstraint(
            model_name='salarytable',
            constraint=models.UniqueConstraint(fields=('start_date', 'salary_table', 'salary_level', 'salary_adjustment'), name='salary_table_unique'),
        ),
    ]
