# Generated by Django 3.2 on 2021-06-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstc', '0002_auto_20210606_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytableexcel',
            name='sheet_name',
            field=models.CharField(max_length=10, verbose_name='シート名'),
        ),
        migrations.AlterField(
            model_name='salarytableexcel',
            name='start_cell',
            field=models.CharField(max_length=10, verbose_name='データ開始セル'),
        ),
    ]
