# Generated by Django 3.2 on 2021-06-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstc', '0003_auto_20210608_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytableexcel',
            name='cols',
            field=models.IntegerField(default=1, verbose_name='号俸'),
        ),
        migrations.AddField(
            model_name='salarytableexcel',
            name='rows',
            field=models.IntegerField(default=1, verbose_name='級'),
        ),
    ]
