# Generated by Django 3.2 on 2021-06-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstc', '0004_auto_20210608_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytableexcel',
            name='sny_flg',
            field=models.BooleanField(default=True, verbose_name='再任用有無'),
        ),
    ]
