"""
Django settings for keju project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from os import path, getenv
from django.conf.locale.ja import formats as ja_formats

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-we274qpq)$hp^7!b-kkk(kkl&ybk_u7$uyzbf419-!3&e@=k+^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'checked_csv',
    'commndata',
    'keju',
    'pstc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'keju.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'keju.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'keju',
        'HOST': 'localhost',
        'PORT': 5432,
        'USER': 'keju',
        'PASSWORD': 'p09olp09ol',
        'ATOMIC_REQUESTS': True
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGES = (
    ('en-us', 'English'),
    ('ja', 'Japanese'),
)

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = 'master.User'

LOCALE_PATHS = (
    path.join(BASE_DIR, 'locale/'),
    path.join(Path(__file__).resolve().parent, 'locale/'),
)

USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = (3, 0)

ja_formats.DATE_FORMAT = 'Y/m/d'                    # default: 'Y年n月j日'
ja_formats.DATETIME_FORMAT = 'Y/m/d H:i:s'          # default: 'Y年n月j日G:i'
ja_formats.SHORT_DATETIME_FORMAT = 'Y/m/d H:i'      # default: 'Y/m/d G:i'

ja_formats.DATE_INPUT_FORMATS = ['%Y/%m/%d', '%Y-%m-%d', '%Y%m%d']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}.{msecs:0<3.0f}][{module}:{filename}:{funcName}][{levelname}][{process:d}][{thread:d}]: {message}',
            # 'datefmt' : '%Y/%m/%d %H:%M:%S',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}.{msecs:0<3.0f}][{module}][{levelname}]: {message}',
            'datefmt' : '%Y/%m/%d %H:%M:%S',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }
    },
    'handlers': {
        'sql_log': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': '/temp/django_sql_log.log',
            'encoding':'utf8',
        },
        'root_log': {
            'level': 'WARNING',
            'filters': ['require_debug_false'],
            # TimedRotatingFileHandler must be used with --noreload option
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'when': 'midnight',
            'interval': 5,
            'backupCount': 100,
            'formatter': 'simple',
            'filename': '/temp/django_root_log.log',
            'encoding':'utf8',
        },
        'keju_log': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': '/temp/keju_log.log',
            'encoding':'utf8',
        },
        'console': {
            'level': 'DEBUG',
            'formatter': 'verbose',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        }
    },
    'root': {
        'handlers': ['console', 'root_log', 'keju_log'],
        'level': 'INFO',
    },
    'loggers': {
        'keju': {
            'handlers': ['console', 'keju_log'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console', ],
            'level': getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'django.db.backends': {
            'level': 'INFO',
            'handlers': ['sql_log'],
        }
    }
}